name: Build Windows x64

on:
  workflow_dispatch
  
jobs:
  build-windows-x64:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: ExtractSdlVersion
        run: dotnet fsi .\Scripts\ExtractSdlVersion.fsx
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
      - name: Cmake Setup
        run: cmake --preset Main
      - name: Cmake Build
        run: cmake --build --target SDL3-shared --config Release --preset Release
      - uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-x64'
          path: ./build/SDL/Release/SDL3.dll
          overwrite: true
      - name: Build Package
        run: dotnet build --no-restore -c Release ./Packages/Coplt.Sdl3.Native.Win.x64/Coplt.Sdl3.Native.Win.x64.csproj
      - uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-x64.nupkg'
          path: ./Packages/Coplt.Sdl3.Native.Win.x64/bin/Release/*.nupkg
          overwrite: true
