name: Build

on:
  workflow_dispatch
  
jobs:
  build-windows-x64:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
      - name: Cmake Setup
        run: cmake --preset Main
      - name: Cmake Build
        run: cmake --build --target SDL3-shared --config Release --preset Release
      - uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-x64'
          path: ./build/SDL/Release/SDL3.dll
          overwrite: true
          
  build-windows-arm64:
    runs-on: windows-11-arm
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
      - name: Cmake Setup
        run: cmake --preset Main
      - name: Cmake Build
        run: cmake --build --target SDL3-shared --config Release --preset Release
      - uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-arm64'
          path: ./build/SDL/Release/SDL3.dll
          overwrite: true
  