name: Build Windows Arm64

on:
  workflow_dispatch
  
jobs:
  build-windows-arm64:
    runs-on: windows-11-arm
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: ExtractSdlVersion
        run: dotnet fsi .\Scripts\ExtractSdlVersion.fsx
      - name: Cmake Setup
        run: cmake --preset WinArm64
      - name: Cmake Build
        run: cmake --build --target SDL3-shared --config Release --preset "Release (WinArm64)"
      - uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-arm64'
          path: ./build/arm/SDL/Release/SDL3.dll
          overwrite: true
  