name: Build Native

on:
  workflow_dispatch

jobs:
  build-meta-package:
    uses: ./.github/workflows/build-native-meta-package.yml
  build-windows-x64:
    uses: ./.github/workflows/build-win-x64.yml
  build-windows-arm64:
    uses: ./.github/workflows/build-win-arm64.yml
  build-linux-x64:
    uses: ./.github/workflows/build-linux-x64.yml
  build-linux-arm64:
    uses: ./.github/workflows/build-linux-arm64.yml
  build-macos:
    uses: ./.github/workflows/build-macos.yml
