name: Build Windows Arm64

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      nupkg-artifact:
        value: ${{ jobs.build-windows-arm64.outputs.nupkg-artifact }}
  
jobs:
  build-windows-arm64:
    runs-on: windows-11-arm
    outputs:
      nupkg-artifact: ${{ steps.upload-nupkg-artifact.outputs.artifact-id }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: ExtractSdlVersion
        run: dotnet fsi ./Scripts/ExtractSdlVersion.fsx
      - name: Cmake Setup
        run: cmake --preset WinArm64
      - name: Cmake Build
        run: cmake --build --target SDL3-shared --config Release --preset "Release (WinArm64)"
      - uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-arm64'
          path: ./build/arm/SDL/Release/SDL3.dll
          overwrite: true
      - name: Build Package
        run: dotnet build --no-restore -c Release ./Packages/Coplt.Sdl3.Native.Win.Arm64/Coplt.Sdl3.Native.Win.Arm64.csproj
      - id: upload-nupkg-artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'native-windows-arm64.nupkg'
          path: ./Packages/Coplt.Sdl3.Native.Win.Arm64/bin/Release/*.nupkg
          overwrite: true
  