name: Publish to Nuget

on:
  workflow_dispatch:
    inputs:
      nupkg-artifact:
        type: string
        description: artifact id
      nupkg-artifact-name:
        type: string
        description: artifact name
  workflow_call:
    inputs:
      nupkg-artifact:
        type: string
        description: artifact id
      nupkg-artifact-name:
        type: string
        description: artifact name

jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.nupkg-artifact-name }}
          artifact-ids: ${{ inputs.nupkg-artifact }}
          path: ./artifact
      - name: Display structure of downloaded files
        run: ls -R ./artifact
      - name: Publish
        run: dotnet fsi ./Scripts/PublishNuget.fsx
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        