on:
  workflow_dispatch

jobs:
  build-windows-x64:
    uses: ./.github/workflows/build-win-x64.yml
    
  publish-to-nuget:
    runs-on: ubuntu-latest
    needs:
      - build-windows-x64
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
