name: Publish to Nuget

on:
  workflow_dispatch:
    inputs:
      nupkg-artifact:
        required: true
        type: string
        description: artifact id
  workflow_call:
    inputs:
      nupkg-artifact:
        required: true
        type: string
        description: artifact id

jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ inputs.nupkg-artifact }}
          path: ./artifact
      - name: Display structure of downloaded files
        run: ls -R
